### ISSUE TITLE
ESS AC POWERSETPOINT can't be set

### ISSUE THREAD

**Issue by AminShAT** [sfstar/hass-victron#100] opened 2023-07-13 11:49 UTC
This field is used to engage battery load from the grid. The integration shows changes in the value correctly, but it's value can't be set from within the home assistant.

**Comment by AminShAT** [comment] 2023-07-13 12:13
Addition:

The values are not displayed in the entities when changed from outside, they are just logged correctly.

**Comment by LeoWinterDE** [comment] 2023-08-14 12:16
Have you tried deleting once and adding the victron connection again? Then it worked for me.

**Comment by sfstar** [comment] 2024-03-15 15:43
Hello @AminShAT and thank you for opening this issue,

Could you perhaps provide me with a screenshot of your hass-victrons integration configuration?
This would help me in narrowing down the cause of your issue since the values provided in the integrations configuration are used to calculate safe min/max values for entities.

**Comment by AminShAT** [comment] 2024-03-15 17:43
Du you mean this one?

![image](https://github.com/sfstar/hass-victron/assets/133445212/b9bf86c2-f2bd-407b-8a27-fc86201ea1bf)

**Comment by sfstar** [comment] 2024-03-17 13:50
Exactly.
In your configuration you specify an AC per phase current limit of 0.
Since this is the base for calculating the powersetpoint range (namely grid V * grid A) this results in the behaviour you are experiencing.
By setting the current limit to an value in AMPS you will see the slider entity become useable for setting the powersetpoint.

**Comment by AminShAT** [comment] 2024-03-17 16:10
I understand, but this is inconsistent with the behavior in Victron itself and from outside via Nodered, where it is possible. Not sure, if it would be best practice, to have 2 places to maintain system characteristics. Aren't those values available within Victron?

**Comment by sfstar** [comment] 2024-03-18 14:04
Unfortunatly the possibility of discovering settings in the GX device is limited via the modbus server.
Therefore, a register scan for all valid unit id's was implemented and amps/voltages are explicitly asked for.
Since, the integration cannot retrieve the values from the GX device.

**Comment by AminShAT** [comment] 2024-03-18 16:54
Alright. So set it to 65A. Will try next time. I used actually to force load my batteries.

**Comment by sfstar** [comment] 2024-03-29 13:50
Great to hear.
I'm closing the issue as resolved.

**Closed by sfstar** 2024-03-29 13:50 UTC
