### ISSUE TITLE
entities disappear

### ISSUE THREAD

**Issue by OlePZ9** [sfstar/hass-victron#21] opened 2023-01-03 14:24 UTC
After having installed the integration successfully, the integration found 509 entities, both solarchargers included. After a while (reboot?) some of the entities disappeared.
![image](https://user-images.githubusercontent.com/60582161/210375840-25af87ee-315d-4a65-8c4d-5cf36989780c.png)
![image](https://user-images.githubusercontent.com/60582161/210376010-9da6af02-a142-4911-ac76-dd1514c55c04.png)
![image](https://user-images.githubusercontent.com/60582161/210376129-1092c659-83d2-4f74-943b-499c12393f47.png)
![image](https://user-images.githubusercontent.com/60582161/210376234-aef83e77-a757-480a-a99a-e8c3fdbad455.png)

What happened here?

**Comment by OlePZ9** [comment] 2023-01-03 19:35
![image](https://user-images.githubusercontent.com/60582161/210428480-e26cf3c4-a0d0-49d9-96d6-abf634c1613f.jpeg)

Since adding the integration, this all is not working anymore...

**Comment by OlePZ9** [comment] 2023-01-03 19:36
![image](https://user-images.githubusercontent.com/60582161/210428689-7900ff96-8690-4f9a-9e19-9f300510e874.jpeg)

**Comment by sfstar** [comment] 2023-01-03 19:40
What are the errors you see when you click the logs link that you can see in your screenshot?
Are there any errors on that page that were generated by this integration?

**Comment by OlePZ9** [comment] 2023-01-03 20:47
Honestly speaking, I have no idea what the reason is. The same setup with my manual Modbus integration in another virtual machine clone works fine

**Comment by OlePZ9** [comment] 2023-01-03 20:47
![image](https://user-images.githubusercontent.com/60582161/210438938-d67ecdc6-e021-467b-8934-0c9e9990a529.jpeg)

**Comment by OlePZ9** [comment] 2023-01-03 20:48
![image](https://user-images.githubusercontent.com/60582161/210438965-98838a13-ca48-4069-a114-7b250f191ce1.jpeg)

**Comment by OlePZ9** [comment] 2023-01-03 20:48
![image](https://user-images.githubusercontent.com/60582161/210438996-67728863-be1c-4994-b844-71b8dfe9cf45.jpeg)

**Comment by OlePZ9** [comment] 2023-01-03 21:08
Braamvr may had explained the reason in his issue about missing data from his grid meter

**Comment by OlePZ9** [comment] 2023-01-03 21:09
![image](https://user-images.githubusercontent.com/60582161/210441781-55203156-5bed-403d-b766-bd1eb96926cc.png)

**Comment by OlePZ9** [comment] 2023-01-03 21:11
As you can see in the second picture, the integration also uses 0, in my Modbus setup I am using 100

**Comment by OlePZ9** [comment] 2023-01-03 21:17
https://www.victronenergy.com/live/ccgx:modbustcp_faq

**Comment by OlePZ9** [comment] 2023-01-03 21:17
![image](https://user-images.githubusercontent.com/60582161/210442817-c3451bfd-20eb-40e7-a72f-a68a1e594536.jpeg)

**Comment by sfstar** [comment] 2023-01-04 17:47
Thank you,
This information is really helpfull in understanding what is going on at your ends.
I currently do not have a ve.can devices (planned for the near future) so in order to reproduce your issues I would need to check if I can reproduce it in demo mode.
Since this has a large impact on the functioning of my system I will need some time in order to find a suitable window for down-time.

**Comment by OlePZ9** [comment] 2023-01-04 18:11
Thank you for spending time on that! I really appreciate your work and altogether everything looks very promising! If you haben an idea where to change something, I could check, as my productive system runs idependently from the testing environment. Actually it would be too hard to change all names of my Victron entities and dashboards to get it working on my system. My yaml is about 2000 lines....

**Comment by Raini20** [comment] 2023-01-21 20:39
Hello I just made a little workaround for the same problem:

`automation reload_victron:
    alias: reload victron
    description: 'reload integration if entity unknown/unavailable'
    trigger:
      - platform: state
        entity_id: sensor.victron_solarcharger_yield_power_100
        to:
          - "unknown"
          - "unavailable"
    action:
        service: homeassistant.reload_config_entry
        data: {}
        target:
            entity_id: sensor.victron_solarcharger_yield_power_100
    mode: single`
    
    I wrote this in my configuration.yaml and if the trigger entity becomes unavailable/unknown it reloads the integration. For me it automates the reloading and I don't have any data holes anymore

**Comment by askpatrickw** [comment] 2023-09-07 05:49
Not sure if this new information or not ... 

I had been working all day with some GPS values from my Cerbo:  `states('sensor.victron_gps_latitude_0')`

After upgrading to 2023.9 all my `_0` were no longer active new `_100' entries existed.
`states('sensor.victron_gps_latitude_100')`

**Comment by sfstar** [comment] 2024-05-19 08:52
The issue has been shipped in the latest release (v0.3.0) closing issue as resolved.
Feel free to re-open if the issue persists with the v0.3.0 release

**Closed by sfstar** 2024-05-19 08:52 UTC
Labels: shipped, startup unavailability
