### ISSUE TITLE
using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']

### ISSUE THREAD

**Issue by Next9999** [sfstar/hass-victron#42] opened 2023-02-02 15:43 UTC
Tks again for all the work
i removed the integration, reload the new HACS and reinstall the integration.

=============================================
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:674
Integration: Sensor (documentation, issues)
First occurred: 08:25:20 (29 occurrences)
Last logged: 08:25:21

Entity sensor.victron_battery_system_numberofmodulesonline_235 (<class 'custom_components.victron.sensor.VictronSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_battery_system_numberofmodulesblockingcharge_235 (<class 'custom_components.victron.sensor.VictronSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_battery_system_numberofmodulesblockingdischarge_235 (<class 'custom_components.victron.sensor.VictronSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_inverter_info_firmwareversion_239 (<class 'custom_components.victron.sensor.VictronSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.victron_inverter_info_productid_239 (<class 'custom_components.victron.sensor.VictronSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('voltage') it is using; expected one of ['V', 'mV']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by sfstar** [comment] 2023-02-03 19:48
v0.0.8 is now released with a fix for this issue.
Please install it to resolve this issue.
For now I will be closing this issue report in favor of #25 since it has the same root cause.
Feel free to re-open if the issue isn't resolved after updating and restarting.

**Closed by sfstar** 2023-02-03 19:48 UTC
Labels: bug
