### ISSUE TITLE
Battery min SOC - input

### ISSUE THREAD

**Issue by VSLRA** [sfstar/hass-victron#18] opened 2022-12-27 10:39 UTC
Hi.
amazing work! Thanks for this integration.

I tried to use `sensor.victron_settings_ess_batterylife_minimumsoc` for dashboard slider, in order to change minimum SOC, based on individual need, but this entity does not allowed me to write any data. Is there any possibility to change SOC via your integration?

Example:
![Snímek obrazovky 2022-12-27 v 17 03 10](https://user-images.githubusercontent.com/121484905/209691644-83251cdb-409a-4571-82a7-c525af714f59.png)

**Comment by sfstar** [comment] 2022-12-31 09:10
Hello and thank you for opening this issue.
I see that you have found that can BMS'es unfortunately don't populate the charge and discharge registers.
While they still are available to be queried by this integration.

As to you issue with setting the minimum soc.
I just tested setting the minimum soc from my production instance and everything worked as intended.
There was only a small "bug" that I set the value to 27% and that the vrm console showed the value to be set as 25%.
Most likely victron only displays or allows setting this value to a multiple of 5.

In case you can't set the batterylife minimumsoc entity make sure that you enable write support in the integrations configuration.

**Comment by CTRDevelopments** [comment] 2023-01-08 14:12
I dont think it will accept any value that is not a multiple of 5. I dont think it rounds, it just errors the command

**Comment by sfstar** [comment] 2023-03-06 17:26
This issue should now be adressed in the latest release containing the fix made by @ChristophPech.
I will close this issue if there are no further reports in the coming weeks.

**Closed** 2023-05-05 12:57 UTC
Labels: bug
