### ISSUE TITLE
Device Address 0/100

### ISSUE THREAD

**Issue by OlePZ9** [sfstar/hass-victron#47] opened 2023-02-07 22:11 UTC
Recognizing the devices on 0/100 still is unstable. First scan found the solarcharger on 0, after a restart of HA the entities weren’t available anymore. A new scan found them now under 100. this issue had been mentioned before but now it seems to be sure that it has to do with handling of devices under this address. Would a manual fixation of this address maybe help?

**Comment by pos-ei-don** [comment] 2023-02-08 05:15
Had the same yesterday. But i also had Devices which really got a new id in the vrm. Strange. Sorry to ask, I am new to HA.
Is a manual fixation as you mentioned possible with automatic created entities? When I try to do, everything is greyed out. So all my Utility and Templates stopped working and I lost historical data...

**Comment by OlePZ9** [comment] 2023-02-08 18:41
It really wrote new (wrong ) addresses from this integration into VRM? That is very dangerous and would be a severe argument against the write option. What devices (numbers) were / are affected?

**Comment by pos-ei-don** [comment] 2023-02-08 19:09
No. Vmr or venusos itself change the ids after a reboot. I have no idea why. But i had this before using this dintegradion from time to time. 
I had to manual ly Update everything as All entities, all Templates and all Plots where suddently wrong.

**Comment by Next9999** [comment] 2023-03-14 15:03
Same for me, the device address skip from 0 / 100... leaving the GPS  (0) with no data
![image](https://user-images.githubusercontent.com/54117519/225043825-0383ee7d-5f1f-4ad2-951c-fcb58fc46a1c.png)

**Comment by tastyllama** [comment] 2023-03-27 23:19
Re scanning the integration seems to bring the device 0 back online for me.  Every reboot device 0 goes Unknown, then I go to Integrations/devices and reconfigure and rescan the victron integration.  Then it works.

**Comment by OlePZ9** [comment] 2023-05-12 08:57
Now, after working flawlewss since months, the upgrade to the recent version brought back this issue.
My Solarcharber (MPPT 450/100) now got back Address 0 instead of 100 before. This is unreliable. As from Victron side "100" is the correct one, that should be editable during configuration, so thzat scanning does not bring up the wrong value

**Comment by OlePZ9** [comment] 2023-05-12 09:22
even "better" the solarchager 450/100 now is being called "generator" with device ID 0
![image](https://github.com/sfstar/hass-victron/assets/60582161/8673908d-d970-434f-b868-049d4ec571cc)

**Comment by OlePZ9** [comment] 2023-05-12 09:22
as stated in my last two comments

**Comment by gnissahr** [comment] 2023-05-15 09:48
I have similar issues, but with a Lynx Shunt. It alternates between ID 0 and 100. The change happens with a HA restart for example. The Cerbo was not rebooted in the mean time.

**Comment by andlo** [comment] 2023-06-11 18:54
Me to - after restart Homeassistant GPS isnt loaded - and a rescan will fix that until next restart of homeassistant :( 

But when it works it works great :) 

I connect to at VenusOS runnng in my RV throu a ZeroTier VPN connection. So in teory the problem could be that the modbus cant connect when initialized due to the tnetwork connection isnt up at the same time.

**Comment by Snooz82** [comment] 2023-10-29 18:26
I have similar issues.

butni think it is due to a bug on the Victron side that ID 100 is double used for non „system“ devices.

![image](https://github.com/sfstar/hass-victron/assets/41592183/f449f9cb-54e8-4922-b798-2603cef2663f)
https://www.victronenergy.com/live/ccgx:modbustcp_faq


As you can see 0 and 100 are same and point to the same device.

but in my case the Solar Charger is the one that occasionally is unknown until rediscovering devices manually.

See the 100 is assigned to the solar charger and to com.victronenergy.system and also com.systemenergy.hub4

![image](https://github.com/sfstar/hass-victron/assets/41592183/c31fcb49-6931-4691-a423-135167a3188e)

I have to figure out how to regenerate or change the Modbus TCP IDs for the Solar Charger.

**Comment by Snooz82** [comment] 2023-10-29 18:52
Even though it imho is not the fault of this integration, a workaround on this side seems possible.

please let this issue open until anyone has found out how to change the ids to a unique one.

**Comment by Snooz82** [comment] 2023-10-29 19:46
I think i managed to fix it.

I could change settings of the "problematic" devide, in my case the SolarCharger, so that it gets a new Modbus TCP Device ID.

When connected via SSH to the Venus device, open the settings.xml in /data/conf. 

Like:
`nano /data/conf/settings.xml` 

you have to change the id of the device, that you have identified as the malicious one altering between 0 and 100.
In my case it was stored like this:
`<ClassAndVrmInstance type="s" default="solarcharger:0" silent="False">solarcharger:0</ClassAndVrmInstance>`

So i changed the `default` attribute and the text to `solarcharger:290` which i guessed was not used.
After reboot it looked like this and the Modbus TCP ID is now changed to `237` which is also showing up as such in Home Assistant.

```
  ...
  <Devices>
   ...
    <vecan_socketcan_can0_CXXXXXXXXXXXXXX>
      <ClassAndVrmInstance type="s" default="solarcharger:1" silent="False">solarcharger:290</ClassAndVrmInstance>
    </vecan_socketcan_can0_CXXXXXXXXXXXXXX>
    ...
  </Devices>
```

of course this is now a new device, but that is ok for me.

**Comment by askpatrickw** [comment] 2023-10-31 01:16
Cerbo GX 3.11
Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest
HASS Victron v0.1.5

I can confirm with all the latest everything as _now_ this is still occurring.

**Comment by OlePZ9** [comment] 2023-12-24 12:03
Actually my Solarcharger MPPT 450/100 got Address "0" on Cerbo GX. So after a retart the Solarcharger had been recognized under "Generator" with a new entity name xxx_0 instead of xxx_100. I changed one setting in the file "const.py" under custom_components/victron in line 1336. I added "0" as valis unit id. After a reboot my entities were there again, this was important for me to keep my statistics history
![Victron HA Integration Fix 0 zu 100](https://github.com/sfstar/hass-victron/assets/60582161/06f9e667-1c8a-4d65-899d-43c79ec7fe7a)

**Comment by OlePZ9** [comment] 2023-12-24 12:05
![solarcharger 0](https://github.com/sfstar/hass-victron/assets/60582161/7a2cb6b8-05da-452d-b4ae-dc62ccdd60f6)

**Comment by subby28** [comment] 2024-04-26 08:19
Just came to thank you for the fix. I've had this issue for many years and haven't been able to work it out. Adding 0 to valid unit IDs and now sorted it and no more reconfiguring every time HA restarts!! Thankyou.

**Comment by sfstar** [comment] 2024-04-26 14:44
Hello @subby28,

Could you perhaps test the 'main' version of the integration? This should contain the fix in the integration code to assign non system/settings registers to unit 0. If someone with an unit 0 system test the change, I will be able to create a new release that resolves this issue for all users without the need for manual changes to the integration

**Comment by OlePZ9** [comment] 2024-04-27 10:01
How can I test the main version of the integration. I am using the official release

**Comment by sfstar** [comment] 2024-04-27 10:19
You can use the instructions provided in this comment (from another issue):
https://github.com/sfstar/hass-victron/issues/182#issuecomment-1998254266
Thanks in advance for taking the time to test the changes

**Comment by subby28** [comment] 2024-04-27 13:17
> Hello @subby28,
> 
> Could you perhaps test the 'main' version of the integration? This should contain the fix in the integration code to assign non system/settings registers to unit 0. If someone with an unit 0 system test the change, I will be able to create a new release that resolves this issue for all users without the need for manual changes to the integration

Just tested it and it's fixed the issue!

**Comment by the78mole** [comment] 2024-04-30 08:32
When I apply the fix and I compare the the devices, it seems to mix in ESS/Cerbox GX stuff into the ID 0 charger:
Charger 1 (correct):
![image](https://github.com/sfstar/hass-victron/assets/7723396/9c868377-c807-4535-bf55-758d05c12f7e)
Charger 0 (incorrect mixin)
![image](https://github.com/sfstar/hass-victron/assets/7723396/9b28b1f7-cb32-422c-8f80-cc7ecb81270b)

**Comment by sfstar** [comment] 2024-04-30 16:42
Hello @the78mole,

Could you perhaps install the latest main commit and collect debug logging / attach this to this ticket so I can troubleshoot the issue you are having?

**Comment by the78mole** [comment] 2024-04-30 21:34
Uh, will be hard this week. Maybe tomorrow, if it does not get too late.
I also first need to check, how to apply the main branch to the custom component...

**Comment by sfstar** [comment] 2024-05-19 08:52
The issue has been shipped in the latest release (v0.3.0) closing issue as resolved.
Feel free to re-open if the issue persists with the v0.3.0 release

**Closed by sfstar** 2024-05-19 08:52 UTC
Labels: shipped, startup unavailability

**Comment by the78mole** [comment] 2024-05-21 13:30
For the time being, it looks OK... Not broken yet.

**Comment by OlePZ9** [comment] 2025-07-14 14:57
It looks like there still is sometimes trouble with the Address 0/100. At least since the newest update my MPPT450/100 on Adress 0 is lot there anymore. I've had this in the past from time to time, under Address 100 the entities are not there anymore. Wouldnt it be a possibility to be able to chose the right number manually, as the auto scan does not work safely? If I would know where the numbers,that had been found during the auto scan had been stored, I would change them manually, but I cannot find them under the files of the integration.

<img width="313" height="898" alt="Image" src="https://github.com/user-attachments/assets/0eb41d39-eff3-4279-8bdd-114ef5dc5870" />
The entities of the MPPT are not listet separately but under "System"
<img width="1050" height="907" alt="Image" src="https://github.com/user-attachments/assets/2a3e22d7-d517-4f83-b244-989616edd6b8" />

<img width="1369" height="767" alt="Image" src="https://github.com/user-attachments/assets/1b36c8ba-1f76-4db7-be22-8d99d34f64d8" />
