### ISSUE TITLE
SOC = 0%

### ISSUE THREAD

**Issue by Drasek** [sfstar/hass-victron#130] opened 2023-10-05 13:26 UTC
I got wrong values for the SoC in my installation:

![image](https://github.com/sfstar/hass-victron/assets/19518683/ce030cef-7035-4e50-942e-49a9bbdd1a01)
![image](https://github.com/sfstar/hass-victron/assets/19518683/402f1093-4b39-496c-b961-e4b68c0d4c68)

If i have a look inside the device i see that the soc has the right value:
![image](https://github.com/sfstar/hass-victron/assets/19518683/679036e9-3983-4b8a-86be-dda3e1de0eca)

I can only match the charge/discharge data, not the soc - where does the system gets the soc from?
![image](https://github.com/sfstar/hass-victron/assets/19518683/a70aa4d2-e7dd-4847-be03-1ceabefd4982)

System:
Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231002.0 - latest

Victron:
Product | Cerbo GX
Firmware version | v3.10

Battery: Batrium LiFePo4 selfbuild system

Thank you very much for your help!

**Comment by askpatrickw** [comment] 2023-10-09 21:13
@Drasek can you post the YAML for your items. I'd like to see the full names of the sensors. I have had similar issues and I might be able to help find a pattern.

**Comment by jumoog** [comment] 2023-11-12 13:46
The `CCGX-Modbus-TCP-register-list-3.10.xlsx` states that these values are `Not supported by CAN.Bus BMS batteries.` If you are using a CAN.Bus BMS battery, you will always see the value 0.

**Comment by angyp** [comment] 2024-03-05 06:01
Guys the issue is when you enable write in the integration you have to select the "The DC voltage of your battery in V" and you only have the option of lifepo4_12v, lifepo4_24v, lifepo4_48v and selecting any of these removes the SOC probably because they are CAN bus types. But what if you have a 48V AGM battery?

**Comment by sfstar** [comment] 2024-03-29 07:16
The release (v0.2.0) has been shipped.
Closing issue, feel free to re-open if the issue persists with the new release

**Closed by sfstar** 2024-03-29 07:16 UTC
Labels: bug, shipped
